# -*- coding: utf-8 -*-
"""dashboard-ventas -cacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-UNzIgvvRFykeRo7stcjnaCotu7Ul0r

Bloque 1 —  importar librerías y subir el CSV
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Definir los nombres de las columnas que coincidan con la estructura esperada del archivo
column_names = ['id_venta', 'producto', 'ciudad', 'canal_venta', 'cantidad', 'precio_unidad', 'costo_unidad', 'tiene_descuento', 'hora_dia']

# Leer el archivo CSV, saltando las dos primeras líneas (encabezado incompleto y fila mal formada)
# y asignando los nombres de columna definidos a partir de la tercera línea.
df = pd.read_csv('/content/ventas_cacao_co.csv', sep=',', header=None, skiprows=2, names=column_names, engine='python', on_bad_lines='warn')

"""Bloque 2 — Limpiar y preparar los datos"""

# Convierte la hora de texto "14:00" a número entero 14
df['hora_num'] = df['hora_dia'].str.split(':').str[0].astype(int)

# Ingreso total por fila = precio × cantidad
df['ingreso_total'] = df['precio_unidad'] * df['cantidad']

# Costo total por fila = costo unitario × cantidad
df['costo_total'] = df['costo_unidad'] * df['cantidad']

# Ganancia neta por fila = ingresos − costos
df['ganancia'] = df['ingreso_total'] - df['costo_total']

print("✅ Datos listos:")
print(df.head())

"""Bloque 3 — Calcular los 3 KPIs"""

# KPI 1: producto con más unidades vendidas en el año
producto_top = df.groupby('producto')['cantidad'].sum().idxmax()

# KPI 2: ciudad con mayor ganancia total acumulada
ciudad_top = df.groupby('ciudad')['ganancia'].sum().idxmax()

# KPI 3: porcentaje de pedidos que incluyeron descuento
pct_descuento = (df['tiene_descuento'] == 'Si').sum() / len(df) * 100

print(f"Producto más vendido : {producto_top}")
print(f"Ciudad más rentable  : {ciudad_top}")
print(f"Pedidos con descuento: {pct_descuento:.1f}%")

"""Bloque 4 — Dashboard unificado"""

COLORES = ['#4E2A0A', '#7B3F1E', '#A0522D', '#C8834A', '#E8B87A']
sns.set_theme(style='whitegrid', palette=COLORES)

fig = plt.figure(figsize=(18, 12), facecolor='#FDF6EE')
gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)

fig.suptitle('☕  Dashboard de Rescate — Cacao & Co.',
             fontsize=20, fontweight='bold', color='#2E1A0E', y=1.01)

# ── GRÁFICO 1: Ganancia por producto ─────────────────────────────────────────
ax1 = fig.add_subplot(gs[0, 0])

ganancia_prod = (df.groupby('producto')['ganancia']
                 .sum()
                 .sort_values(ascending=False)
                 .reset_index())

sns.barplot(data=ganancia_prod, x='producto', y='ganancia',
            palette=COLORES[:4], ax=ax1)

for barra in ax1.patches:
    alto = barra.get_height()
    ax1.text(barra.get_x() + barra.get_width() / 2, alto + 5000,
             f'${alto:,.0f}', ha='center', va='bottom',
             fontsize=8, color='#2E1A0E', fontweight='bold')

ax1.set_title('① Ganancia neta por producto', fontsize=11,
              fontweight='bold', color='#2E1A0E')
ax1.set_xlabel('')
ax1.set_ylabel('Ganancia total (COP)', fontsize=9)
ax1.tick_params(axis='x', rotation=15)
ax1.set_facecolor('#FDF6EE')

# ── GRÁFICO 2: Boxplot descuento vs precio regular ───────────────────────────
ax2 = fig.add_subplot(gs[0, 1])

sns.boxplot(data=df, x='tiene_descuento', y='ganancia',
            palette={'No': '#C8834A', 'Si': '#4E2A0A'},
            ax=ax2, width=0.5)

sns.stripplot(data=df, x='tiene_descuento', y='ganancia',
              color='#E8B87A', alpha=0.6, size=6, jitter=True, ax=ax2)

ax2.set_title('② Descuento vs ganancia por transacción', fontsize=11,
              fontweight='bold', color='#2E1A0E')
ax2.set_xlabel('¿Tiene descuento?', fontsize=9)
ax2.set_ylabel('Ganancia por venta (COP)', fontsize=9)
ax2.set_facecolor('#FDF6EE')

# ── GRÁFICO 3: Unidades por ciudad ───────────────────────────────────────────
ax3 = fig.add_subplot(gs[0, 2])

unidades_ciudad = (df.groupby('ciudad')['cantidad']
                   .sum()
                   .sort_values(ascending=True)
                   .reset_index())

ax3.barh(unidades_ciudad['ciudad'], unidades_ciudad['cantidad'],
         color=COLORES[:3], edgecolor='white', linewidth=0.5)

for i, val in enumerate(unidades_ciudad['cantidad']):
    ax3.text(val + 0.3, i, str(val),
             va='center', fontsize=9, color='#2E1A0E', fontweight='bold')

ax3.set_title('③ Unidades vendidas por ciudad', fontsize=11,
              fontweight='bold', color='#2E1A0E')
ax3.set_xlabel('Total unidades', fontsize=9)
ax3.set_ylabel('')
ax3.set_facecolor('#FDF6EE')

# ── GRÁFICO 4: Flujo de ventas por hora y canal ─────────────────────────────
ax4 = fig.add_subplot(gs[1, 0:2])

ventas_hora_canal = df.pivot_table(
    index='hora_num', columns='canal_venta',
    values='ganancia', aggfunc='sum', fill_value=0)

for i, canal in enumerate(ventas_hora_canal.columns):
    ax4.plot(ventas_hora_canal.index, ventas_hora_canal[canal],
             marker='o', linewidth=2.5, markersize=7,
             label=canal, color=COLORES[i])

ax4.set_title('④ Flujo de ganancias por hora y canal', fontsize=11,
              fontweight='bold', color='#2E1A0E')
ax4.set_xlabel('Hora del día', fontsize=9)
ax4.set_ylabel('Ganancia total (COP)', fontsize=9)
ax4.legend(title='Canal', fontsize=9)
ax4.set_xticks(sorted(df['hora_num'].unique()))
ax4.set_facecolor('#FDF6EE')

# ── PANEL 5: KPIs de alerta temprana ──────────────────────────────────────────
ax5 = fig.add_subplot(gs[1, 2])
ax5.axis('off')

from matplotlib.patches import FancyBboxPatch
fondo = FancyBboxPatch((0.03, 0.05), 0.94, 0.90,
                        boxstyle="round,pad=0.02",
                        facecolor='#4E2A0A', edgecolor='#C8834A',
                        linewidth=2, transform=ax5.transAxes)
ax5.add_patch(fondo)

ax5.text(0.5, 0.88, '⑤  Panel de alerta temprana',
         transform=ax5.transAxes, ha='center',
         fontsize=11, fontweight='bold', color='#E8B87A')

ax5.text(0.1, 0.70, '🏆  Producto estrella',
         transform=ax5.transAxes, fontsize=9, color='#C8834A', fontweight='bold')
ax5.text(0.1, 0.59, producto_top,
         transform=ax5.transAxes, fontsize=10, color='white', fontweight='bold')

ax5.text(0.1, 0.47, '📍  Ciudad más rentable',
         transform=ax5.transAxes, fontsize=9, color='#C8834A', fontweight='bold')
ax5.text(0.1, 0.36, ciudad_top,
         transform=ax5.transAxes, fontsize=10, color='white', fontweight='bold')

ax5.text(0.1, 0.24, '🎟️  Pedidos con descuento',
         transform=ax5.transAxes, fontsize=9, color='#C8834A', fontweight='bold')
ax5.text(0.1, 0.13, f'{pct_descuento:.1f}% del total',
         transform=ax5.transAxes, fontsize=10, color='white', fontweight='bold')

# ── GUARDAR Y MOSTRAR ──────────────────────────────────────────────────────────
plt.savefig('dashboard_cacao_co.png', dpi=150,
            bbox_inches='tight', facecolor='#FDF6EE')
plt.show()
print("✅ Dashboard generado y guardado como dashboard_cacao_co.png")
